package Lab8;
import java.awt.*;
import simView.*;

public class routing extends ViewableDigraph
{

	public routing()
	{
		super("routing");
    	
		ViewableAtomic g = new sender("sender", 10);
		ViewableAtomic r = new router("router", 10);
    	
		add(g);
		add(r);
		for(int i=1;i<=5;i++) {
			ViewableAtomic p = new reciever("reciever #"+i,10);
			add(p);
			System.out.println("constructing the whole routing");
			addCoupling(r,"out"+i,p,"in");
		}
		addCoupling(g,"out",r,"in");
		addCoupling(r,"out",g,"in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("reciever #5")).setPreferredLocation(new Point(720, 281));
        ((ViewableComponent)withName("sender")).setPreferredLocation(new Point(63, 279));
        ((ViewableComponent)withName("reciever #1")).setPreferredLocation(new Point(413, 164));
        ((ViewableComponent)withName("reciever #3")).setPreferredLocation(new Point(525, 118));
        ((ViewableComponent)withName("reciever #4")).setPreferredLocation(new Point(774, 132));
        ((ViewableComponent)withName("reciever #2")).setPreferredLocation(new Point(535, 258));
        ((ViewableComponent)withName("router")).setPreferredLocation(new Point(289, 416));
    }
}
