package yeonsup;
import java.awt.*;
import simView.*;

public class gproc extends ViewableDigraph
{

	public gproc()
	{
		super("gproc");
    	
		ViewableAtomic g = new genr("g", 10);
		ViewableAtomic p = new proc("p", 10);
		//ViewableAtomic t = new transd("t", 70);
    	
		add(g);
		add(p);
		//add(t);
  
		addCoupling(g, "out", p, "in"); //from g's out to p's in
		/*
		addCoupling(g, "out", t, "ariv");
		
		addCoupling(p, "out", t, "solved");
		*/
     
		addCoupling(p, "out", g, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("p")).setPreferredLocation(new Point(681, 121));
        ((ViewableComponent)withName("g")).setPreferredLocation(new Point(63, 279));
    }
}
