package lab6;
import java.awt.*;
import simView.*;

public class whole_accumulator extends ViewableDigraph
{

	public whole_accumulator()
	{
		super("whole_accumulator");
    	
		ViewableAtomic g = new user("user", 10);
		ViewableAtomic p = new accumulator("accumulator", 10);
		//ViewableAtomic t = new transd("t", 70);
    	
		add(g);
		add(p);
		//add(t);
  
		addCoupling(g, "out", p, "in");
		addCoupling(p,"out",g,"in");
	
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("user")).setPreferredLocation(new Point(165, 159));
        ((ViewableComponent)withName("accumulator")).setPreferredLocation(new Point(446, 431));
    }
}
