package Lab9;
import simView.*;
import java.awt.*;

public class math extends ViewableDigraph
{
	
	public math()
	{
		this("math");
	}
	
	public math(String name)
	{
		super(name);
		
		addInport("in"); 
		addOutport("out");
		
		ViewableAtomic r = new router("router",10);
		ViewableAtomic a0 = new cal("add",10,0);
		ViewableAtomic a1 = new cal("mul",10,1);
		ViewableAtomic a2 = new acc("acc",10);//그냥 내가 바꾼것
		add(r);
		add(a0);
		add(a1);
		add(a2);

		addCoupling(this, "in", r, "in");

		addCoupling(r, "out0", a0, "in");
		addCoupling(r, "out1", a1, "in");
		addCoupling(r,"out2",a2,"in");
		
		addCoupling(a0,"out",this,"out");
		addCoupling(a1, "out", this, "out");
		addCoupling(a2, "out", this, "out");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(463, 297);
        ((ViewableComponent)withName("router")).setPreferredLocation(new Point(14, 148));
        ((ViewableComponent)withName("add")).setPreferredLocation(new Point(116, 68));
        ((ViewableComponent)withName("acc")).setPreferredLocation(new Point(229, 218));
        ((ViewableComponent)withName("mul")).setPreferredLocation(new Point(207, 136));
    }
}
