package Lab9;
import java.awt.*;
import simView.*;

public class user_math extends ViewableDigraph 
{

	public user_math()
	{
		super("user_math");
		
		ViewableAtomic u = new user("user", 25);
		ViewableDigraph  m = new math("math");

		add(u);
		add(m);

		addCoupling(u, "out", m, "in");

		addCoupling(m, "out", u, "in");
	}
	
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(980, 644);
        ((ViewableComponent)withName("math")).setPreferredLocation(new Point(418, 217));
        ((ViewableComponent)withName("user")).setPreferredLocation(new Point(50, 50));
    }
 }
