package lab4;
import java.awt.*;
import simView.*;

public class modified_gpt extends ViewableDigraph
{

	public modified_gpt()
	{
		super("gpt");
    	
		ViewableAtomic g = new genr("g", 30);
		System.out.println("gpt constructor runs, calling genr");
		ViewableAtomic p = new proc("p", 55);
		ViewableAtomic t = new transd("t", 1000);//modified
    	
		add(g);
		add(p);
		add(t);
  
		addCoupling(g, "out", p, "in");
		addCoupling(g, "out", t, "ariv");
		
		addCoupling(p, "out", t, "solved");
     
		addCoupling(t, "out", g, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("p")).setPreferredLocation(new Point(472, 437));
        ((ViewableComponent)withName("g")).setPreferredLocation(new Point(63, 279));
        ((ViewableComponent)withName("t")).setPreferredLocation(new Point(576, 121));
    }
}
